import 'package:neon_flap1_game/core/theme/app_theme.dart';
import 'package:neon_flap1_game/models/character.dart';

/// The 24-character roster for the premium Character Store.
///
/// Character #1 is free. Prices and stats escalate together: more expensive
/// characters float better, have tighter (more forgiving) hitboxes, more
/// precise control and stronger coin attraction — but never to the point of
/// trivialising the game.
class CharactersData {
  const CharactersData._();

  static const List<Character> roster = [
    Character(
      id: 'nova',
      name: 'Nova',
      price: 0,
      isFree: true,
      primary: NeonPalette.cyan,
      accent: NeonPalette.white,
      stats: CharacterStats(),
      description: 'Standard issue courier bird. Balanced flight profile.',
    ),
    Character(
      id: 'pulse',
      name: 'Pulse',
      price: 800,
      isFree: false,
      primary: NeonPalette.magenta,
      accent: NeonPalette.cyan,
      stats: CharacterStats(coinAttraction: 1.3),
      description: 'Magnetised plumage pulls in coins from afar.',
    ),
    Character(
      id: 'volt',
      name: 'Volt',
      price: 1000,
      isFree: false,
      primary: NeonPalette.yellow,
      accent: NeonPalette.red,
      stats: CharacterStats(jumpPrecision: 1.15),
      description: 'Precision wings for crisp aerial taps.',
    ),
    Character(
      id: 'glitch',
      name: 'Glitch',
      price: 1300,
      isFree: false,
      primary: NeonPalette.green,
      accent: NeonPalette.purple,
      stats: CharacterStats(control: 1.2),
      description: 'Responsive feathers, snappy mid-air control.',
    ),
    Character(
      id: 'spectre',
      name: 'Spectre',
      price: 1700,
      isFree: false,
      primary: NeonPalette.purple,
      accent: NeonPalette.cyan,
      stats: CharacterStats(gravityScale: 0.94, hitboxScale: 0.95),
      description: 'Phase-shifted frame: lighter gravity, tighter form.',
    ),
    Character(
      id: 'quasar',
      name: 'Quasar',
      price: 2200,
      isFree: false,
      primary: NeonPalette.cyan,
      accent: NeonPalette.magenta,
      stats: CharacterStats(
          coinAttraction: 1.4, jumpPrecision: 1.1),
      description: 'Long-range coin tractor and steady flight.',
    ),
    Character(
      id: 'ember',
      name: 'Ember',
      price: 2800,
      isFree: false,
      primary: NeonPalette.red,
      accent: NeonPalette.yellow,
      stats: CharacterStats(control: 1.25, jumpPrecision: 1.1),
      description: 'Combustion wings tuned for agile manoeuvres.',
    ),
    Character(
      id: 'cyber',
      name: 'Cyber',
      price: 3500,
      isFree: false,
      primary: NeonPalette.green,
      accent: NeonPalette.cyan,
      stats: CharacterStats(gravityScale: 0.92, hitboxScale: 0.92),
      description: 'Reinforced feathers shrink the danger zone.',
    ),
    Character(
      id: 'phantom',
      name: 'Phantom',
      price: 4500,
      isFree: false,
      primary: NeonPalette.purple,
      accent: NeonPalette.magenta,
      stats: CharacterStats(
          control: 1.3, coinAttraction: 1.45),
      description: 'Ghost protocol: supreme handling and magnetism.',
    ),
    Character(
      id: 'aurora',
      name: 'Aurora',
      price: 5500,
      isFree: false,
      primary: NeonPalette.cyan,
      accent: NeonPalette.green,
      stats: CharacterStats(
          gravityScale: 0.9, jumpPrecision: 1.2),
      description: 'Ion lift wings deliver a floaty, precise glide.',
    ),
    Character(
      id: 'nebula',
      name: 'Nebula',
      price: 7000,
      isFree: false,
      primary: NeonPalette.magenta,
      accent: NeonPalette.purple,
      stats: CharacterStats(
          hitboxScale: 0.88, coinAttraction: 1.5),
      description: 'Micro-frame with a powerful coin vortex.',
    ),
    Character(
      id: 'titan',
      name: 'Titan',
      price: 9000,
      isFree: false,
      primary: NeonPalette.yellow,
      accent: NeonPalette.white,
      stats: CharacterStats(
          gravityScale: 0.89, control: 1.3),
      description: 'Heavy plumage, surprisingly nimble thrust.',
    ),
    Character(
      id: 'zenith',
      name: 'Zenith',
      price: 12000,
      isFree: false,
      primary: NeonPalette.cyan,
      accent: NeonPalette.yellow,
      stats: CharacterStats(
          jumpPrecision: 1.25,
          hitboxScale: 0.86,
          coinAttraction: 1.55),
      description: 'Peak courier tech: precise, compact, magnetic.',
    ),
    Character(
      id: 'singularity',
      name: 'Singularity',
      price: 15000,
      isFree: false,
      primary: NeonPalette.purple,
      accent: NeonPalette.cyan,
      stats: CharacterStats(
          gravityScale: 0.87,
          control: 1.35,
          hitboxScale: 0.85),
      description: 'Collapsed-core frame bending gravity to your will.',
    ),
    Character(
      id: 'cosmos',
      name: 'Cosmos',
      price: 20000,
      isFree: false,
      primary: NeonPalette.purple,
      accent: NeonPalette.green,
      stats: CharacterStats(gravityScale: 0.86, control: 1.32),
      description: 'Null-gravity frame with reactive thrusters.',
    ),
    Character(
      id: 'eclipse',
      name: 'Eclipse',
      price: 25000,
      isFree: false,
      primary: NeonPalette.red,
      accent: NeonPalette.purple,
      stats: CharacterStats(gravityScale: 0.85, hitboxScale: 0.84),
      description: 'Shadow-forged hull nearly vanishes on impact.',
    ),
    Character(
      id: 'nova_prime',
      name: 'Nova Prime',
      price: 32000,
      isFree: false,
      primary: NeonPalette.cyan,
      accent: NeonPalette.red,
      stats: CharacterStats(control: 1.38, jumpPrecision: 1.28),
      description: 'Upgraded flight computer. Pin-point responses.',
    ),
    Character(
      id: 'infinity',
      name: 'Infinity',
      price: 42000,
      isFree: false,
      primary: NeonPalette.magenta,
      accent: NeonPalette.yellow,
      stats: CharacterStats(coinAttraction: 1.65, jumpPrecision: 1.28),
      description: 'Endless magnetic field and unrivaled precision.',
    ),
    Character(
      id: 'omega_plus',
      name: 'Omega Plus',
      price: 55000,
      isFree: false,
      primary: NeonPalette.green,
      accent: NeonPalette.white,
      stats: CharacterStats(
          gravityScale: 0.84,
          control: 1.42,
          jumpPrecision: 1.32,
          hitboxScale: 0.81,
          coinAttraction: 1.65),
      description: 'Beyond apex. Every stat maxed.',
    ),
    Character(
      id: 'myth',
      name: 'Myth',
      price: 70000,
      isFree: false,
      primary: NeonPalette.purple,
      accent: NeonPalette.yellow,
      stats: CharacterStats(coinAttraction: 1.7),
      description: 'Aura of legend pulls coins from off-screen.',
    ),
    Character(
      id: 'legend',
      name: 'Legend',
      price: 90000,
      isFree: false,
      primary: NeonPalette.green,
      accent: NeonPalette.red,
      stats: CharacterStats(control: 1.45, gravityScale: 0.84),
      description: 'Legendary handling with weightless drift.',
    ),
    Character(
      id: 'apex',
      name: 'Apex',
      price: 120000,
      isFree: false,
      primary: NeonPalette.cyan,
      accent: NeonPalette.magenta,
      stats: CharacterStats(jumpPrecision: 1.35, hitboxScale: 0.80),
      description: 'Sharpest edges, deadliest aim.',
    ),
    Character(
      id: 'genesis',
      name: 'Genesis',
      price: 160000,
      isFree: false,
      primary: NeonPalette.purple,
      accent: NeonPalette.white,
      stats: CharacterStats(gravityScale: 0.83, coinAttraction: 1.75),
      description: 'Birth of a new era. Near-zero gravity.',
    ),
    Character(
      id: 'universe',
      name: 'Universe',
      price: 220000,
      isFree: false,
      primary: NeonPalette.yellow,
      accent: NeonPalette.green,
      stats: CharacterStats(
          control: 1.5,
          jumpPrecision: 1.35,
          hitboxScale: 0.79,
          coinAttraction: 1.8),
      description: 'The final bird. Master of all dimensions.',
    ),
  ];

  static Character byId(String id) =>
      roster.firstWhere((c) => c.id == id, orElse: () => roster.first);
}
